apiVersion: v1
kind: Service
metadata:
  name: rails
  labels:
    app: drkiq
spec:
  ports:
    - port: 3000
  selector:
    app: drkiq
    tier: rails
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rails
spec:
  replicas: 1
  selector:
    app: drkiq
    tier: rails
  template:
    metadata:
      name: rails
      labels:
        app: drkiq
        tier: rails
    spec:
      containers:
      - name: rails
        image: rails:4
        args: ["rails new --skip-bundle"]
        env:
        - name: DATABASE_URL
          value: "postgres"
        - name: DATABASE_NAME
          value: "rails-kube-demo_production"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: "db-user"
              key: "username"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "db-user-pass"
              key: "password"         
        - name: RAILS_APP
          value: "production"
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: RAILS_SERVE_STATIC_ASSETS
          value: "true"
        - name: REDIS_URL
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: "secret-key-base"
              key: "secret-key-base"
        ports:
        - containerPort: 3000