apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: drkiq
spec:
  ports:
    - port: 6379
  selector:
    app: drkiq
    tier: redis
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    app: drkiq
    tier: redis
  template:
    metadata:
      name: redis
      labels:
        app: drkiq
        tier: redis
    spec:
      containers:
      - name: redis
        image: redis:3.0.5
        ports:
        - containerPort: 6379